### ISSUE TITLE
Patch to work with ABCL

### ISSUE THREAD

**Issue by GoogleCodeExporter** [wmannis/cl-svg#2]
```
I needed to patch CL-SVG from Quicklisp with the attached patch to get it to 
render with ABCL.

The problem stems from ABCL's pretty printer stream, which is apparently not 
equivalent to CL:STREAM in all cases.  

I consider this patch to be a hack which destroys the beauty of the cl-svg 
source code, which needs to be fixed in ABCL as [ticket-223][].

[ticket-223]: http://abcl.org/trac/ticket/223

```

Original issue reported on code.google.com by `evenson....@gmail.com` on 1 Apr 2014 at 7:13

Attachments:
- [cl-svg-streams.diff](https://storage.googleapis.com/google-code-attachments/cl-svg/issue-2/comment-0/cl-svg-streams.diff)

**Comment by easye** [comment]
The patch has been updated as https://github.com/wmannis/cl-svg/pull/11

ABCL has not completely sorted out its schizophrenic relation to streams and there is no firm timeline on when this will be resolved, so I would currently recommend merging the above pull request at all possible in order to get `cl-svg` at least working under ABCL in Quicklisp.  

 Even though I characterized this patch as a "hack" in 2014, this code was used in production for QR codes for a medical document management system for over five years without issues, so it doesn't empirically harm anything.
